name: animal_sounds
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  audioplayers: ^0.13.7
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.1
  firebase_admob: ^0.9.0+10
  flutter_launcher_icons: ^0.6.1
  share: ^0.6.3+5

  #fluttertoast: ^2.2.3

flutter_icons:
  android: true
  image_path: "icon/iconsounds.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
 sdk: '>=2.10.0 <3.0.0'


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
   - assets/images/dog1.jpg
   - assets/images/canard1.jpg
   - assets/images/cat1.jpg
   - assets/images/cat2.jpg
   - assets/images/cat3.jpg
   - assets/images/cat4.jpg
   - assets/images/cat5.jpg
   - assets/images/cat6.jpg
   - assets/images/cat7.jpg
   - assets/images/cat8.jpg
   - assets/images/cat9.jpg
   - assets/images/cat10.jpg
   - assets/images/coq1.jpg
   - assets/images/coq2.jpg
   - assets/images/cow1.jpg
   - assets/images/cow2.jpg
   - assets/images/dind.jpg
   - assets/images/cow3.jpg
   - assets/images/cow4.jpg
   - assets/images/dog2.jpg
   - assets/images/dog3.jpg
   - assets/images/dog4.jpg
   - assets/images/hors1.jpg
   - assets/images/hors2.jpg
   - assets/images/hors3.jpg
   - assets/images/hors4.jpg
   - assets/images/fondapp.jpg
   - assets/images/mouton4.jpg
   - assets/images/mouton5.jpg
   - assets/images/mouton3.jpg
   - assets/images/mouton1.jpg
   - assets/images/mouton2.jpg
   - assets/canard1.mp3
   - assets/cat1.mp3
   - assets/cat2.mp3
   - assets/cat3.mp3
   - assets/cat4.mp3
   - assets/cat5.mp3
   - assets/cat6.mp3
   - assets/cat7.mp3
   - assets/cat8.mp3
   - assets/cat9.mp3
   - assets/coq2.mp3
   - assets/chiken1.mp3
   - assets/chiken2.mp3
   - assets/dog1.mp3
   - assets/dog2.mp3
   - assets/dog3.mp3
   - assets/dog4.mp3
   - assets/dogdoberman.mp3
   - assets/hors1.mp3
   - assets/hors2.mp3
   - assets/hors3.mp3
   - assets/horswolking.mp3
   - assets/sheep1.mp3
   - assets/horse4.mp3
   - assets/vache1.mp3
   - assets/vache2.mp3
   - assets/vache3.mp3
   - assets/sheep2.mp3
   - assets/sheep3.mp3
   - assets/sheep4.mp3
   - assets/sheep5.mp3
   - assets/bibi.mp3
   - assets/images/dogdog.png
   - assets/images/catcat.png
   - assets/images/vachvache.png
   - assets/images/moutonmouton.png
   - assets/images/horshors.png
   - assets/images/coqcoq.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages